name: GE
on:
  workflow_dispatch:
    inputs:
      app_id:
        description: app_id
        required: false
    branches:
      - main
concurrency:
  group: wait
  cancel-in-progress: false
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: P-ToyStore/SteamManifestCache_Pro
          submodules: recursive
          token: ${{ secrets.TOKEN }}
      - name: 设置 Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 配置 Git
        run: |
          git fetch --all
          git branch -a
