name: GE
on:
  workflow_dispatch:
    branches:
      - main
concurrency:
  group: wait
  cancel-in-progress: false
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: 配置 Git
        run: |
          git remote add B https://github.com/BlankTMing/ManifestAutoUpdate2.git
          git remote add A https://github.com/BlankTMing/ManifestAutoUpdate.git
          git fetch A
          for branch in $(git branch -r | grep "A/" | sed 's/A\///'); do
            git push B "A/$branch:refs/heads/$branch"
          done
