name: GE
on:
  workflow_dispatch:
    branches:
      - main
concurrency:
  group: wait
  cancel-in-progress: false
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: 配置 Git
        run: |
          # 添加远程仓库 A 和 B
          git remote add B https://github.com/BlankTMing/ManifestAutoUpdate2.git
          git remote add A https://github.com/BlankTMing/ManifestAutoUpdate.git
          git fetch A
          git push B +refs/heads/*:refs/heads/*
