name: GE
on:
  workflow_dispatch:
    branches:
      - main
concurrency:
  group: wait
  cancel-in-progress: false
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: BlankTMing/ManifestAutoUpdate
          submodules: recursive
          token: ${{ secrets.TOKEN }}
      - name: 设置 Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: 配置 Git
        run: |
          git push origin --delete 3508771_5883014022774933376
          #git push origin --delete $(git ls-remote --tags origin | awk '{print $2}' | sed 's/refs\/tags\///' | grep -E '[0-9]+_[0-9]+')
          #git ls-remote --heads origin | cut -f2 | sed 's/refs\/heads\///' | tr '\n' ','
