name: Push
on:
  workflow_dispatch:
    branches:
      - main
concurrency:
  group: wait
  cancel-in-progress: false
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          repository: BlankTMing/ManifestAutoUpdate_Code
          submodules: recursive
          token: ${{ secrets.TOKEN }}
      - name: 设置 Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 配置 Git
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email github-actions[bot]@github.com
          git remote set-url origin https://github.com/BlankTMing/ManifestAutoUpdate
      - name: 配置并删除分支
        run: |
          python test2.py
